// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czlyqjaeuthbvmdgrpuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bHlxamFldXRoYnZtZGdycHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODUwMzUsImV4cCI6MjA2MDA2MTAzNX0.L9lE_gSwwjq4873nJWvKlgdqTy3ODPgRyQshMW_a2T0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);